# Generated by Django 5.1.1 on 2024-09-30 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adresse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strasse', models.CharField(max_length=100)),
                ('hausnummer', models.CharField(max_length=10)),
                ('plz', models.CharField(max_length=10)),
                ('ort', models.CharField(max_length=50)),
                ('bundesland', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
